name: Sync to Malaga-FCA-Group

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false  # <--- ESTO ES LA CLAVE MÁGICA

      - name: Push to Group Repository
        run: |
          # Ahora no hace falta borrar nada, porque 'checkout' no ha guardado nada.
          
          # 1. Configurar el remoto con tu TOKEN explícito
          git remote add target https://neuroimaginador:${{ secrets.API_TOKEN_GITHUB }}@github.com/Malaga-FCA-Group/fcaR.git
          
          # 2. Empujar
          git push --force target origin/master:master
          git push --force --tags target
