name: Sync to Malaga-FCA-Group

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Group Repository
        run: |
          # 1. Intentar borrar la auth del bot (|| true evita el error 5 si no existe)
          git config --global --unset-all http.https://github.com/.extraheader || true
          
          # 2. Configurar el remoto con tu TOKEN
          git remote add target https://neuroimaginador:${{ secrets.API_TOKEN_GITHUB }}@github.com/Malaga-FCA-Group/fcaR.git
          
          # 3. Empujar
          git push --force target origin/master:master
          git push --force --tags target
