name: Sync to Malaga-FCA-Group

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Importante para traer todo el historial

      - name: Push to Group Repository
        run: |
          # 1. Configurar el remoto destino usando el TOKEN en la URL
          # Esto fuerza a git a usar tu identidad, no la del bot
          git remote add target https://neuroimaginador:${{ secrets.API_TOKEN_GITHUB }}@github.com/Malaga-FCA-Group/fcaR.git

          # 2. Empujar expl√≠citamente la rama master/main y los tags
          # Nota: Ajusta 'master' si tu rama principal se llama 'main'
          git push --force target origin/master:master
          git push --force --tags target
